kind: pipeline
name: default

steps:
- name: tests
  image: python:3
  environment:
    SPOTIPY_CLIENT_ID:
      from_secret: SPOTIPY_CLIENT_ID
    SPOTIPY_CLIENT_SECRET:
      from_secret: SPOTIPY_CLIENT_SECRET
    SPOTIFY_SCOPES: 'user-read-private user-read-email'
  commands:
  - pip install pipenv
  - pipenv install
  - pipenv run pytest

