kind: pipeline
name: default

steps:
- name: tests
  image: python:3
  environment:
    SPOTIPY_CLIENT_ID:
      from_secret: SPOTIPY_CLIENT_ID
    SPOTIPY_CLIENT_SECRET:
      from_secret: SPOTIPY_CLIENT_SECRET
    SPOTIFY_SCOPES: 'user-read-private user-read-email'
  commands:
  - pip install pipenv
  - pipenv install -d
  - pipenv run pytest

- name: notification
  image: appleboy/drone-telegram
  token:
    from_secret: token
  to:
    from_secret: username
  message: >
      {{build.link}}
    {{#success build.status}}
      Build {{build.number}} succeeded. Good job.
    {{else}}
      Build {{build.number}} failed. Fix me please.
    {{/success}}
      {{commit.sha}} - {{commit.link}}
      ----
      {{commit.message}}
  when:
    status:
    - failure
    - success
